import {test,expect} from 'bun:test';import {promises as fs} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {selectTranscriptScope,transcriptPlannerInput,validateTranscriptDecision} from '../planner';import {StudioVisualFlow,type StudioSource} from '../studio-flow';import {buildSummaryEvidence} from '../../summary/evidence';import {planSummaryChunks} from '../../summary/chunks';
import {DEFAULT_CONFIG} from '../../config/defaults';import {runCommand} from '../../jobs/command';import {hashFile} from '../../jobs/store';import {withHeavyAdmission,readHeavyStatus} from '../../runtime/heavy-admission';
const transcript={version:1 as const,provider:'whisper-cpp' as const,model:'synthetic',language:'pt',text:'Large synthetic history',segments:Array.from({length:300},(_,i)=>({start:i/100,end:(i+1)/100,text:'Segmento sintético '+i+'; gráfico a revisar.'}))};
test('explicit interval preserves absolute IDs/time, counts omitted boundaries, no silent truncation, summary contains only selected text',()=>{
 const s=selectTranscriptScope(transcript,3,1.2,1.3);expect(s.withinLimits).toBe(true);expect(s.segments[0].id).toBe('s000120');expect(s.segments[0].start).toBe(1.2);expect(s.segments).toHaveLength(10);expect(s.omittedBefore).toBe(120);expect(s.omittedAfter).toBe(170);
 const partial=selectTranscriptScope(transcript,3,1.205,1.295);expect(partial.omittedIntersecting).toBe(2);expect(partial.segments.every(s=>s.start>=1.205&&s.end<=1.295)).toBe(true);
 expect(selectTranscriptScope(transcript,3).withinLimits).toBe(false);expect(()=>transcriptPlannerInput(transcript,3)).toThrow('scope');for(const range of [[-1,2],[2,1],[0,4]])expect(()=>selectTranscriptScope(transcript,3,...range as [number,number])).toThrow();
 const ids=s.segments.map(s=>s.id),e=buildSummaryEvidence(transcript,'a'.repeat(64),8000,ids);expect(e.segments).toHaveLength(10);expect(e.segments[0].id).toBe('s000120');const chunks=planSummaryChunks(transcript,'a'.repeat(64),undefined,24000,undefined,ids);expect(chunks[0].text).toContain('sintético 120');expect(chunks[0].text).not.toContain('sintético 0;');expect(chunks[0].evidence.segments).toHaveLength(10);
 const raw={decision:'frames',rationale:'Verificar referência selecionada.',sources:[{segmentId:'s000120',quote:transcript.segments[120].text}],requests:[{timestampSeconds:1.205,reason:'visual-reference',question:'O que aparece?',segmentIds:['s000120']}]};expect(validateTranscriptDecision('a'.repeat(64),transcript,3,raw,s).plan.requests[0].timestampSeconds).toBe(1.205);expect(()=>validateTranscriptDecision('a'.repeat(64),transcript,3,{...raw,sources:[{segmentId:'s000000',quote:transcript.segments[0].text}]},s)).toThrow();
});
async function fixture(run:(s:StudioSource,f:StudioVisualFlow,c:{planner:number;vision:number;summary:number},root:string,set:(x:string)=>void)=>Promise<void>){
 const root=await fs.mkdtemp(join(tmpdir(),'transcript-scope-')),old=globalThis.fetch,c={planner:0,vision:0,summary:0};let mode='frames';
 try{const path=join(root,'synthetic.mp4');await runCommand('ffmpeg',['-nostdin','-v','error','-f','lavfi','-i','testsrc2=size=160x90:rate=5','-t','3','-c:v','mpeg4',path]);const config=structuredClone(DEFAULT_CONFIG);config.summary.ollamaUrl='http://127.0.0.1:11434';const s={key:'synthetic-key',jobId:'synthetic-job',path,mediaHash:await hashFile(path),config,transcript};
 globalThis.fetch=(async(url,init)=>{expect(new URL(String(url)).hostname).toBe('127.0.0.1');const body=JSON.parse(String(init?.body));if(String(url).endsWith('/api/show'))return Response.json({model_info:{architecture:'synthetic'},capabilities:['vision','completion']});const input=JSON.parse(body.messages[1].content);
 if(input.segments){c.planner++;expect(input.segments).toHaveLength(10);expect(input.segments[0].id).toBe('s000120');expect(input.segments[0].start).toBe(1.2);const raw=mode==='none'?{decision:'none',rationale:'Trecho textual suficiente.',sources:[],requests:[]}:{decision:'frames',rationale:'Detalhe visual não descrito.',sources:[{segmentId:'s000120',quote:input.segments[0].text}],requests:[{timestampSeconds:1.205,reason:'visual-reference',question:'Que detalhe é legível?',segmentIds:['s000120']}]};return Response.json({message:{content:JSON.stringify(raw)}});}
 if(body.model==='vision-fixture'){c.vision++;const f=input.frames[0];return Response.json({message:{content:JSON.stringify({observations:[{frameFile:f.file,timestampSeconds:f.timestampSeconds,frameSha256:f.sha256,text:'Observação sintética não é interpretação real.',uncertainty:'uncertain'}]})}});}
 c.summary++;expect(input.evidence.segments).toHaveLength(10);expect(input.evidence.segments[0].id).toBe('s000120');expect(JSON.stringify(input)).not.toContain('sintético 0;');return Response.json({message:{content:JSON.stringify({title:'Resumo parcial fixture',overview:'Revisar somente trecho selecionado.',topics:[],decisions:[],actionItems:[],citations:[{section:'overview',index:0,segmentIds:['s000120'],uncertainty:'uncertain'}],limitations:[]})}});}) as typeof fetch;
 await run(s,new StudioVisualFlow(join(root,'app')),c,root,x=>mode=x);
 }finally{globalThis.fetch=old;await fs.rm(root,{recursive:true,force:true});}
}
test('long transcript scope→planner→consent→frame→partial summary keeps absolute origin and sends no omitted history',async()=>fixture(async(s,f,c)=>{
 const cap=await f.check(s.config,'vision-fixture','summary-fixture'),scope=await f.scope(s,1.2,1.3);expect(scope.omittedCount).toBe(290);const plan=await f.plan(s,cap.id,true,scope.id);const p=await f.previewPlan(s,plan.id);expect(p.scope!.key).toBe(scope.key);await expect(f.confirm(s,p.id,true,'changed')).rejects.toThrow('consent');const result=await f.confirm(s,p.id,true,p.consentKey);expect(result.timestampSeconds).toBe(1.205);expect(result.summary.support.references[0]).toEqual({id:'s000120',start:1.2,end:1.21});expect(result.summary.limitations).toContain('Resumo parcial do intervalo selecionado; restante da transcrição omitido.');expect(c).toEqual({planner:1,vision:1,summary:1});
}));
test('over-limit scope is visible but never silently truncated or sent; none preserves existing media and performs no image/summary',async()=>fixture(async(s,f,c,root,set)=>{
 const cap=await f.check(s.config,'vision-fixture','summary-fixture'),tooBig=await f.scope(s,0,3);expect(tooBig.withinLimits).toBe(false);expect(tooBig.includedCount).toBe(300);expect(tooBig.segments).toEqual([]);await expect(f.plan(s,cap.id,true,tooBig.id)).rejects.toThrow('scope');expect(c.planner).toBe(0);
 set('none');const scope=await f.scope(s,1.2,1.3),p=await f.plan(s,cap.id,true,scope.id);expect(p.decision).toBe('none');await expect(f.previewPlan(s,p.id)).rejects.toThrow('frames plan');expect(c).toEqual({planner:1,vision:0,summary:0});expect(await hashFile(s.path)).toBe(s.mediaHash);expect(await fs.access(join(root,'app/results')).then(()=>true,()=>false)).toBe(false);
}));
test('changing/canceling selection while queued aborts before model, and revoked scope cannot be reused',async()=>fixture(async(s,f,c)=>{
 const cap=await f.check(s.config,'vision-fixture','summary-fixture'),scope=await f.scope(s,1.2,1.3);let release!:()=>void;const blocker=withHeavyAdmission('pipeline','blocker',async()=>new Promise<void>(r=>release=r));
 try{for(let i=0;i<100&&!release;i++)await Bun.sleep(10);const pending=f.plan(s,cap.id,true,scope.id).then(()=>Error('unexpected'),e=>e);for(let i=0;i<100;i++){if((await readHeavyStatus()).waiting.length)break;await Bun.sleep(10);}f.cancel(s.key,'',scope.id);release();await blocker;expect(await pending).toBeInstanceOf(Error);expect(c).toEqual({planner:0,vision:0,summary:0});await expect(f.plan(s,cap.id,true,scope.id)).rejects.toThrow('selection');
 }finally{release?.();await blocker;}
}));
test('selection revocation invalidates completed plan and prepared consent, no vision/summary can follow',async()=>fixture(async(s,f,c)=>{
 const cap=await f.check(s.config,'vision-fixture','summary-fixture'),scope=await f.scope(s,1.2,1.3),plan=await f.plan(s,cap.id,true,scope.id),preview=await f.previewPlan(s,plan.id);f.cancel(s.key,'',scope.id);await expect(f.previewPlan(s,plan.id)).rejects.toThrow('plan');await expect(f.confirm(s,preview.id,true,preview.consentKey)).rejects.toThrow('consent');expect(c).toEqual({planner:1,vision:0,summary:0});
}));
test('expired scope refuses preview/confirm without requiring an unrelated purge, and re-plans cannot exhaust shared decisions',async()=>fixture(async(s,_f,c,root)=>{
 let now=Date.now();const f=new StudioVisualFlow(join(root,'ttl-app'),()=>now),cap=await f.check(s.config,'vision-fixture','summary-fixture'),scope=await f.scope(s,1.2,1.3);
 let plan=await f.plan(s,cap.id,true,scope.id);for(let i=0;i<17;i++)plan=await f.plan(s,cap.id,true,scope.id);expect(c.planner).toBe(1);const preview=await f.previewPlan(s,plan.id);now+=300001;await expect(f.previewPlan(s,plan.id)).rejects.toThrow('plan');await expect(f.confirm(s,preview.id,true,preview.consentKey)).rejects.toThrow('consent');expect(c.vision).toBe(0);expect(c.summary).toBe(0);
}));
test('transcript-only none does not lifetime-lock the job to a model identity; attempts still persist',async()=>fixture(async(s,f,c,root,set)=>{
 set('none');let cap=await f.check(s.config,'vision-fixture','summary-fixture'),scope=await f.scope(s,1.2,1.3);await f.plan(s,cap.id,true,scope.id);cap=await f.check(s.config,'another-vision','another-summary');scope=await f.scope(s,1.2,1.3);await f.plan(s,cap.id,true,scope.id);const data=JSON.parse(await fs.readFile(join(root,'app/budget.json'),'utf8'));expect(data.inferences).toBe(2);expect(data.jobs).toEqual({});expect(c).toEqual({planner:2,vision:0,summary:0});
}));
