import {promises as fs} from 'node:fs';
import {join,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {ContextAccess,assertId,digest} from '../agent-context/access';
import {AgentRetrieval} from '../agent-context/retrieval';
import {AnalysisLedger} from './ledger';
import {buildRequest,parseResponse,apiTransport,SYSTEM,type AuthorizedImage,type Transport} from './adapters';
import {estimateCost,type ProviderRecipient} from './contracts';
import {getDefaultJobStateDir} from '../jobs/store';
import {withHeavyAdmission,type AdmissionOptions} from '../runtime/heavy-admission';
import {privateDirectory,assertPrivateDirectoryAncestors,type VisualBudgetPolicy} from '../visual/app-budget';
import {writePrivateArtifact} from '../jobs/artifacts';
export type AnalyzeRequest={requestId:string;grantId:string;recordingId:string;question:string;timestamps:number[];contextOffset?:number};
export class ProviderAnalysis{
 constructor(readonly retrieval=new AgentRetrieval(),readonly transport:Transport|undefined=undefined,readonly ledger=new AnalysisLedger(join(dirname(getDefaultJobStateDir()),'visual-review','provider-analysis')),readonly now=Date.now){}
 async analyze(input:AnalyzeRequest,options:{signal?:AbortSignal;admission?:AdmissionOptions;policy?:VisualBudgetPolicy}={}){
  if(!this.transport)return {available:false,status:'disabled',reason:'Explicit visual API runtime transport disabled; no credential read or provider call'};
  assertId(input.requestId);if(typeof input.question!=='string'||!input.question.trim()||input.question.length>1000||!Array.isArray(input.timestamps)||input.timestamps.length>6||input.timestamps.some(t=>!Number.isFinite(t)||t<0)||input.contextOffset!==undefined&&(!Number.isSafeInteger(input.contextOffset)||input.contextOffset<0))throw Error('Invalid bounded analysis input');
  const initial=await this.retrieval.access.read(input.grantId);if(initial.recipient.kind!=='provider'||!initial.analysis)throw Error('Local agent grant cannot authorize provider analysis');const recipient=initial.recipient,a=initial.analysis;
  const check=async(validateSource=false)=>{options.signal?.throwIfAborted();const g=await this.retrieval.access.require(initial.id,recipient,'frames',input.recordingId);if(g.revision!==initial.revision||digest(g.analysis)!==digest(a))throw Error('Analysis scope/model/budget authorization changed');if(validateSource)await this.retrieval.catalog.validate(g.scope.sources.find(s=>s.id===input.recordingId)!);};
  await check();if(!input.timestamps.length)return {decision:'abstain',overview:'No frames selected; no provider request',observations:[],partial:true,requestId:input.requestId};
  const preflight=estimateCost(a,SYSTEM.length+input.question.length,input.timestamps.length);if(preflight.usd===null&&(!a.acceptUnknownCost||a.estimatedBudgetUsd!==null))throw Error('Unknown model tariff; explicit unknown-cost choice and no monetary hard cap required');
  let context='',contextSources:unknown[]=[];
  if(initial.data.includes('context')&&a.maxContextCharacters){const c=await this.retrieval.getContext({grantId:initial.id,recipient,recordingId:input.recordingId,offset:input.contextOffset,maxCharacters:4096},options);if(c.available&&c.context){for(const e of c.context.excerpts){const part=e.text.slice(0,a.maxContextCharacters-context.length);if(!part)break;context+=part;contextSources.push({artifactSha256:e.artifactSha256,charOffset:e.charOffset,timing:e.timing,timestamps:e.timestamps,providedTextSha256:createHash('sha256').update(part).digest('hex'),truncated:part.length!==e.text.length});}}}
  const fingerprint=digest({input,recipient,revision:initial.revision,analysis:a,context,contextSources,mediaHash:initial.scope.sources.find(s=>s.id===input.recordingId)!.sha256});
  const previous=await this.ledger.find(input.requestId);if(previous){if(previous.grantId!==initial.id||previous.fingerprint!==fingerprint)throw Error('Request ID reused with changed input/model/scope');await check();if(previous.state!=='completed')return {requestId:input.requestId,status:previous.state,cost:'unknown or reserved; do not auto-retry',retransmitted:false};return withHeavyAdmission('vision','provider-cache-'+input.requestId,async()=>{await check(true);const cached=await this.readResult(input.requestId);await check(true);return cached;},{...options.admission,signal:options.signal});}
  const evidence=await this.retrieval.getFrames({grantId:initial.id,recipient,recordingId:input.recordingId,timestamps:input.timestamps,supportsImages:true},options);
  const images:AuthorizedImage[]=[];for(const frame of evidence.frames){const buffer=await fs.readFile(frame.file);if(buffer.length!==frame.bytes||createHash('sha256').update(buffer).digest('hex')!==frame.sha256)throw Error('Frame changed before provider request');images.push({sha256:frame.sha256,mimeType:frame.mimeType,data:buffer.toString('base64'),reference:{requestedTimestampSeconds:frame.requestedTimestampSeconds,decodedTimestampSeconds:frame.decodedTimestampSeconds,precision:frame.precision}});}
  const payload=buildRequest(recipient,a,{question:input.question,context,recordingId:input.recordingId,mediaHash:evidence.mediaHash,frames:images});const estimate=estimateCost(a,SYSTEM.length+input.question.length+context.length+JSON.stringify(contextSources).length+1000,images.length);if(estimate.usd===null&&!a.acceptUnknownCost)throw Error('Unknown model tariff; explicit unknown-cost choice required');
  return withHeavyAdmission('vision','provider-'+input.requestId,async()=>{
   await check(true);const claimed=await this.ledger.claim({requestId:input.requestId,grantId:initial.id,fingerprint,state:'reserved',estimateUsd:estimate.usd,at:this.now()},a.maxRequests,a.estimatedBudgetUsd);if(!claimed)return {requestId:input.requestId,status:'already-reserved',retransmitted:false};
   let dispatched=false;const controller=new AbortController();const cancel=()=>controller.abort(options.signal?.reason||Error('Analysis cancelled'));options.signal?.addEventListener('abort',cancel,{once:true});if(options.signal?.aborted)cancel();const timer=setTimeout(()=>controller.abort(Error('Analysis timed out; provider outcome/cost uncertain')),a.timeoutMs);
   try{
    const configured=options.policy??(await import('../config/load').then(m=>m.loadConfig())).config.visualReview;await this.retrieval.budget.reserve('inference',input.recordingId,JSON.stringify(recipient),configured,false);await check(true);controller.signal.throwIfAborted();dispatched=true;
    const abort=new Promise<never>((_,reject)=>{if(controller.signal.aborted)reject(controller.signal.reason);else controller.signal.addEventListener('abort',()=>reject(controller.signal.reason),{once:true});});
    const raw=await Promise.race([this.transport!({...payload,recipient},controller.signal),abort]);await check(true);controller.signal.throwIfAborted();const parsed=parseResponse(recipient,raw,images);
    const observations=parsed.observations.map((o:any)=>{const f=evidence.frames[o.frameIndex]!;return {...o,recordingId:input.recordingId,mediaHash:evidence.mediaHash,requestedTimestampSeconds:f.requestedTimestampSeconds,decodedTimestampSeconds:f.decodedTimestampSeconds,precision:f.precision};});
    const result={...parsed,observations,requestId:input.requestId,recipient,scope:'bounded visual observations, not full summary',contextSources,estimate,trust:'untrusted-model-output',expiresAt:this.now()+initial.limits.cacheTtlMs};await privateDirectory(join(this.ledger.root,'results'));await writePrivateArtifact(join(this.ledger.root,'results',input.requestId+'.json'),JSON.stringify({result,sha256:digest(result)}));await check(true);await this.ledger.finish(input.requestId,'completed');await check(true);controller.signal.throwIfAborted();return result;
   }catch{await this.ledger.finish(input.requestId,dispatched?'uncertain':'not-sent');return {requestId:input.requestId,status:dispatched?'uncertain':'not-sent',cost:dispatched?'unknown; provider may have accepted request':'reserved estimate; no refund',retransmitted:false};}
   finally{clearTimeout(timer);options.signal?.removeEventListener('abort',cancel);}
  },{...options.admission,signal:options.signal});
 }
 private async readResult(id:string){const path=join(this.ledger.root,'results',assertId(id)+'.json');await assertPrivateDirectoryAncestors(dirname(path));const st=await fs.lstat(path).catch(e=>{if(e.code==='ENOENT')return;throw e;});if(!st)return {requestId:id,status:'result-unavailable',retransmitted:false};if(!st.isFile()||st.isSymbolicLink()||(st.mode&0o077)||st.size>64000)throw Error('Unsafe cached analysis result');const stored=JSON.parse(await fs.readFile(path,'utf8'));if(stored.sha256!==digest(stored.result)||!Number.isFinite(stored.result?.expiresAt))throw Error('Cached analysis result changed');const result=stored.result;if(result.expiresAt<=this.now()){await fs.unlink(path);return {requestId:id,status:'result-expired',retransmitted:false};}return {...result,cacheHit:true};}
}
