export type ProviderRecipient={kind:'provider';id:'openai'|'google';endpoint:string;model:string;capabilities:{vision:true;json:true;source:'user-declared'|'discovered'}};
export type AnalysisOptions={maxRequests:number;maxContextCharacters:number;maxOutputTokens:number;timeoutMs:number;estimatedBudgetUsd:number|null;acceptUnknownCost:boolean;rates:{inputUsdPerMillion:number|null;outputUsdPerMillion:number|null;imageInputTokens:number|null;source:string;asOf:string|null}};
export const endpoints={openai:'https://api.openai.com/v1/responses',google:'https://generativelanguage.googleapis.com/v1beta'} as const;
const only=(value:unknown,keys:string[])=>!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(k=>keys.includes(k));
const integer=(n:number,min:number,max:number)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
const optionalPrice=(n:number|null)=>n===null||Number.isFinite(n)&&n>=0&&n<=1000000;
export function validateProvider(r:ProviderRecipient){if(!only(r,['kind','id','endpoint','model','capabilities'])||!only(r?.capabilities,['vision','json','source'])||r?.kind!=='provider'||!['openai','google'].includes(r.id)||r.endpoint!==endpoints[r.id]||!/^[-a-zA-Z0-9._]{1,160}$/.test(r.model||'')||r.capabilities?.vision!==true||r.capabilities.json!==true||!['user-declared','discovered'].includes(r.capabilities.source))throw Error('Explicit supported provider destination/model/vision+JSON capabilities required');return r;}
export function validateAnalysis(a:AnalysisOptions){if(!only(a,['maxRequests','maxContextCharacters','maxOutputTokens','timeoutMs','estimatedBudgetUsd','acceptUnknownCost','rates'])||!only(a?.rates,['inputUsdPerMillion','outputUsdPerMillion','imageInputTokens','source','asOf'])||!a||!integer(a.maxRequests,1,24)||!integer(a.maxContextCharacters,0,4096)||!integer(a.maxOutputTokens,32,4096)||!integer(a.timeoutMs,100,60000)||!optionalPrice(a.estimatedBudgetUsd)||typeof a.acceptUnknownCost!=='boolean'||!a.rates||![a.rates.inputUsdPerMillion,a.rates.outputUsdPerMillion,a.rates.imageInputTokens].every(optionalPrice)||typeof a.rates.source!=='string'||a.rates.source.length>300||a.rates.asOf!==null&&(typeof a.rates.asOf!=='string'||!Number.isFinite(Date.parse(a.rates.asOf))))throw Error('Invalid explicit analysis limits/tariff metadata');return a;}
export const defaultAnalysis=():AnalysisOptions=>({maxRequests:2,maxContextCharacters:1000,maxOutputTokens:512,timeoutMs:10000,estimatedBudgetUsd:null,acceptUnknownCost:false,rates:{inputUsdPerMillion:null,outputUsdPerMillion:null,imageInputTokens:null,source:'unknown; configure and verify model tariff',asOf:null}});
export function estimateCost(a:AnalysisOptions,textCharacters:number,frames:number){const {rates}=validateAnalysis(a);const known=rates.inputUsdPerMillion!==null&&rates.outputUsdPerMillion!==null&&(frames===0||rates.imageInputTokens!==null);return {usd:known?((Math.ceil(textCharacters/3)+frames*(rates.imageInputTokens||0))*rates.inputUsdPerMillion!+a.maxOutputTokens*rates.outputUsdPerMillion!)/1000000:null,inputTokenEstimate:known?Math.ceil(textCharacters/3)+frames*(rates.imageInputTokens||0):null,method:'configured tariff + rough text chars/3 + configured image token estimate + output cap; not billed tokens or provider hard cap',tariff:rates};}
