import {promises as fs} from 'node:fs';
import {join,resolve} from 'node:path';
import {privateDirectory,assertPrivateDirectoryAncestors} from '../visual/app-budget';
import {writePrivateArtifact} from '../jobs/artifacts';
import {acquireSingleton} from '../runtime/singleton';
import {assertId,digest} from '../agent-context/access';
export type Attempt={requestId:string;grantId:string;fingerprint:string;state:'reserved'|'completed'|'uncertain'|'not-sent';estimateUsd:number|null;at:number};
export class AnalysisLedger{
 constructor(readonly root:string){}
 private async read(){const file=join(this.root,'attempts.json');await assertPrivateDirectoryAncestors(this.root);const st=await fs.lstat(file).catch(e=>{if(e.code==='ENOENT')return;throw e;});if(!st)return [] as Attempt[];if(!st.isFile()||st.isSymbolicLink()||(st.mode&0o077)||st.size>2*1024*1024)throw Error('Unsafe provider ledger');const value=JSON.parse(await fs.readFile(file,'utf8'));if(value.version!==1||!Array.isArray(value.attempts)||value.attempts.length>4096)throw Error('Invalid provider ledger');for(const a of value.attempts){assertId(a.requestId);assertId(a.grantId);if(!/^[a-f0-9]{64}$/.test(a.fingerprint)||!['reserved','completed','uncertain','not-sent'].includes(a.state)||a.estimateUsd!==null&&(!Number.isFinite(a.estimateUsd)||a.estimateUsd<0)||!Number.isFinite(a.at))throw Error('Invalid provider attempt');}if(new Set(value.attempts.map((a:Attempt)=>a.requestId)).size!==value.attempts.length)throw Error('Duplicate provider receipt');return value.attempts as Attempt[];}
 private async transact<T>(run:(attempts:Attempt[])=>Promise<T>){await privateDirectory(this.root);const name='provider-attempts-'+digest(resolve(this.root)).slice(0,24);let lease;const deadline=Date.now()+5000;for(;;){try{lease=await acquireSingleton(name);break;}catch(e){if((e as Error).message!==name+' is already running'||Date.now()>=deadline)throw e;await new Promise(r=>setTimeout(r,25));}}try{const attempts=await this.read();const result=await run(attempts);await writePrivateArtifact(join(this.root,'attempts.json'),JSON.stringify({version:1,attempts}));return result;}finally{await lease.release();}}
 async find(id:string){assertId(id);return (await this.read()).find(a=>a.requestId===id);}
 async snapshot(){const a=await this.read();return {attempts:a.length,knownEstimatedUsd:a.reduce((s,x)=>s+(x.estimateUsd||0),0),unknownCostAttempts:a.filter(x=>x.estimateUsd===null).length,uncertainOutcomes:a.filter(x=>x.state==='uncertain'||x.state==='reserved').length,scope:'user-installation',costNotProviderHardCap:true};}
 async claim(a:Attempt,maxRequests:number,estimatedBudgetUsd:number|null){return this.transact(async attempts=>{const old=attempts.find(x=>x.requestId===a.requestId);if(old){if(old.grantId!==a.grantId||old.fingerprint!==a.fingerprint)throw Error('Request ID reused with different authorized input');return false;}if(attempts.length>=4096||attempts.filter(x=>x.grantId===a.grantId).length>=maxRequests)throw Error('Provider request budget exhausted');if(estimatedBudgetUsd!==null){if(a.estimateUsd===null||attempts.some(x=>x.estimateUsd===null))throw Error('Unknown cost prevents estimated-budget admission; no hard cap promise');if(attempts.reduce((s,x)=>s+x.estimateUsd!,0)+a.estimateUsd>estimatedBudgetUsd)throw Error('Installation estimated budget exhausted');}attempts.push(a);return true;});}
 async finish(id:string,state:Attempt['state']){return this.transact(async attempts=>{const a=attempts.find(x=>x.requestId===id);if(!a)throw Error('Attempt receipt missing');a.state=state;});}
}
