import {promises as fs} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {join,dirname} from 'node:path';
import {getDefaultJobStateDir,hashFile} from '../jobs/store';
import {writePrivateArtifact} from '../jobs/artifacts';
import {verifyLocalOllamaModel,localOllamaAdapterIdentity} from './ollama';
import {probeMedia} from '../jobs/media';
import type {Transcript} from '../jobs/types';
import {selectTranscriptScope} from './planner';
import {planVisualEvidence,type VisualRequest} from './plan';
import {extractVisualEvidence} from './extract';
import {VisualAppBudget,privateDirectory,assertPrivateDirectoryAncestors} from './app-budget';
import type {VisualBudgetPolicy} from './app-budget';
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const root=()=>join(dirname(getDefaultJobStateDir()),'visual-review');
export type PipelineReview={version:1;id:string;createdAt:number;expiresAt:number;mediaHash:string;transcriptHash:string;adapterIdentity:string;summaryIdentity:string;policyRevision:number;visionEndpoint:string;selectorModel:string;visionModel:string;visionDigest:string;summaryDigest:string;origin:'user'|'planner';scope:{startSeconds:number;endSeconds:number;key:string};planKey:string;requests:VisualRequest[];frames:Array<{file:string;timestampSeconds:number;sha256:string;bytes:number}>;consentKey:string};
const path=(id:string)=>{if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid pipeline review id');return join(root(),'pipeline-reviews',id+'.json');};
/** Local preview only. The returned grant is inactive until its exact consentKey is supplied at confirm. */
export async function preparePipelineVisualReview(input:{sourcePath:string;mediaHash:string;transcript:Transcript;adapter:LocalVisualAdapter;adapterIdentity:string;summaryIdentity:string;visionEndpoint:string;selectorModel:string;visionModel:string;startSeconds:number;endSeconds:number;requests:VisualRequest[];policy?:VisualBudgetPolicy;origin?:'user'|'planner';signal?:AbortSignal}){
 input.signal?.throwIfAborted();assertPipelineAdapter(input.adapter,input.visionEndpoint,input.selectorModel,input.visionModel);if(input.adapter.identity!==input.adapterIdentity)throw Error('Pipeline adapter identity differs');const summary=JSON.parse(input.summaryIdentity);if(summary.provider!=='ollama')throw Error('Pipeline visual summary must be local Ollama');const endpoint=new URL(summary.endpoint);if(!['127.0.0.1','localhost','[::1]'].includes(endpoint.hostname)||endpoint.username||endpoint.password||!['http:','https:'].includes(endpoint.protocol))throw Error('Pipeline summary must use loopback');if(input.origin&&input.origin!=='user'&&input.origin!=='planner')throw Error('Invalid review origin');const duration=await probeMedia(input.sourcePath,input.signal);if(await hashFile(input.sourcePath)!==input.mediaHash)throw Error('Pipeline preview media changed');
 const scope=selectTranscriptScope(input.transcript,duration,input.startSeconds,input.endSeconds);if(!scope.withinLimits)throw Error('Pipeline transcript scope exceeds limits');
 const ids=new Set(scope.segments.map(s=>s.id));const plan=planVisualEvidence(input.mediaHash,input.transcript,duration,input.requests);if(!plan.requests.length||plan.requests.length>2||plan.requests.some(r=>((input.origin||'user')==='user'&&r.reason!=='user-request')||!r.segmentIds.length||r.timestampSeconds<scope.startSeconds||r.timestampSeconds>scope.endSeconds||r.segmentIds.some(id=>!ids.has(id))))throw Error('Pipeline preview requests outside approved scope');
 if(input.adapterIdentity!==localOllamaAdapterIdentity(input.visionEndpoint,input.selectorModel,input.visionModel))throw Error('Pipeline adapter/model/endpoint identity differs');
 const visionDigest=await verifyLocalOllamaModel(input.visionEndpoint,input.visionModel,true,input.signal),summaryDigest=await verifyLocalOllamaModel(summary.endpoint,summary.model,false,input.signal);
 const policy=await new VisualAppBudget(root()).reserve('preview',input.mediaHash,hash({adapter:input.adapterIdentity,summary:input.summaryIdentity}),input.policy,false);await privateDirectory(root());const scratch=await fs.mkdtemp(join(root(),'.pipeline-preview-'));
 try{const result=await extractVisualEvidence(plan,input.sourcePath,scratch,{signal:input.signal});const createdAt=Date.now(),id=randomUUID();const fields={version:1 as const,id,createdAt,expiresAt:createdAt+300000,mediaHash:input.mediaHash,transcriptHash:hash(input.transcript),adapterIdentity:input.adapterIdentity,summaryIdentity:input.summaryIdentity,policyRevision:policy.policyRevision,visionEndpoint:new URL(input.visionEndpoint).origin,selectorModel:input.selectorModel,visionModel:input.visionModel,visionDigest,summaryDigest,origin:input.origin||'user',scope:{startSeconds:scope.startSeconds,endSeconds:scope.endSeconds,key:scope.key},planKey:plan.key,requests:plan.requests,frames:result.frames.map(({file,timestampSeconds,sha256,bytes})=>({file,timestampSeconds,sha256,bytes}))};const review={...fields,consentKey:hash(fields)};
 const framePreviews=await Promise.all(result.frames.map(async f=>({...f,frameData:'data:image/jpeg;base64,'+(await fs.readFile(join(scratch,result.key,f.file))).toString('base64')})));
 input.signal?.throwIfAborted();await new VisualAppBudget(root()).assertRevision(policy.policyRevision,input.policy);await privateDirectory(join(root(),'pipeline-reviews'));await cleanupPipelineVisualReviews(Date.now(),false);if((await fs.readdir(join(root(),'pipeline-reviews'))).length>=256)throw Error('Pending pipeline review capacity exhausted');await writePrivateArtifact(path(id),JSON.stringify({kind:'falatrace-pipeline-review',review,sha256:hash(review),revoked:false}));return {...review,framePreviews,requiresConsent:true};
 }finally{await fs.rm(scratch,{recursive:true,force:true});}
}
async function readStored(id:string,checkExpiry=true,allowRevoked=false){const p=path(id);await assertPrivateDirectoryAncestors(dirname(p));const st=await fs.lstat(p);if(!st.isFile()||st.isSymbolicLink()||st.uid!==process.getuid?.()||(st.mode&0o077)||st.size>64000)throw Error('Unsafe pipeline consent');const stored=JSON.parse(await fs.readFile(p,'utf8'));if(!stored||typeof stored!=='object'||stored.kind!=='falatrace-pipeline-review')throw Error('Invalid pipeline consent');if(stored.execution&&stored.executionSha!==hash({owner:stored.owner,execution:stored.execution,artifacts:stored.artifacts}))throw Error('Pipeline execution receipt corrupt');if(stored.revoked===true){if(!allowRevoked)throw Error('Pipeline consent revoked');if(stored.version!==1||stored.id!==id||!Number.isFinite(stored.expiresAt))throw Error('Invalid revoked receipt');return stored;}const r=stored.review;if(!r||stored.sha256!==hash(r)||r.version!==1||r.id!==id||stored.revoked!==false||(checkExpiry&&r.expiresAt<=Date.now())||r.createdAt>Date.now()||r.expiresAt-r.createdAt!==300000)throw Error('Pipeline consent expired/corrupt');return stored;}
async function read(id:string,checkExpiry=true){return (await readStored(id,checkExpiry)).review as PipelineReview;}
async function writeRecord(id:string,record:any){if(record.execution)record.executionSha=hash({owner:record.owner,execution:record.execution,artifacts:record.artifacts});await writePrivateArtifact(path(id),JSON.stringify(record));}
export async function revokePipelineVisualReview(id:string){const lease=await receiptLease(id);try{const review=await read(id);const record=await readStored(id);await writeRecord(id,{kind:'falatrace-pipeline-review',version:1,id,revoked:true,expiresAt:review.expiresAt,owner:record.owner,execution:record.execution,artifacts:record.artifacts});}finally{await lease.release();}}
export async function validatePipelineVisualReview(input:{id:string;consent:boolean;consentKey:string;transcript:Transcript;mediaHash:string;duration:number;adapter:LocalVisualAdapter;adapterIdentity:string;summaryIdentity:string;policy?:VisualBudgetPolicy;signal?:AbortSignal}){
 input.signal?.throwIfAborted();if(input.consent!==true)throw Error('Explicit current pipeline visual consent required');const review=await read(input.id);const {consentKey,...fields}=review;if(consentKey!==hash(fields)||input.consentKey!==consentKey||review.mediaHash!==input.mediaHash||review.transcriptHash!==hash(input.transcript)||review.adapterIdentity!==input.adapterIdentity||review.summaryIdentity!==input.summaryIdentity)throw Error('Pipeline consent/source/provider changed');
 assertPipelineAdapter(input.adapter,review.visionEndpoint,review.selectorModel,review.visionModel);
 const scope=selectTranscriptScope(input.transcript,input.duration,review.scope.startSeconds,review.scope.endSeconds);if(scope.key!==review.scope.key||!scope.withinLimits)throw Error('Pipeline selected transcript changed');const plan=planVisualEvidence(input.mediaHash,input.transcript,input.duration,review.requests);if(plan.key!==review.planKey||!plan.requests.length||plan.requests.length>2||plan.requests.some(r=>r.segmentIds.some(id=>!scope.segments.some(s=>s.id===id))||r.timestampSeconds<scope.startSeconds||r.timestampSeconds>scope.endSeconds))throw Error('Pipeline review plan changed');await new VisualAppBudget(root()).assertRevision(review.policyRevision,input.policy);const summary=JSON.parse(review.summaryIdentity);if(summary.provider!=='ollama'||await verifyLocalOllamaModel(review.visionEndpoint,review.visionModel,true,input.signal)!==review.visionDigest||await verifyLocalOllamaModel(summary.endpoint,summary.model,false,input.signal)!==review.summaryDigest)throw Error('Pipeline model digest changed; fresh consent required');input.signal?.throwIfAborted();return {review,scope,plan};
}

/** Lazy physical TTL cleanup of owned preview receipts only; never traverses media/session/unknown records. */
export async function cleanupPipelineVisualReviews(now=Date.now(),dryRun=true){if(!Number.isFinite(now))throw Error('Invalid pipeline review cleanup clock');const dir=join(root(),'pipeline-reviews');await assertPrivateDirectoryAncestors(dir);const ds=await fs.lstat(dir).catch(e=>{if(e.code==='ENOENT')return;throw e;});if(!ds)return [];if(!ds.isDirectory()||ds.isSymbolicLink()||ds.uid!==process.getuid?.()||(ds.mode&0o077))throw Error('Unsafe pipeline cleanup root');const names=await fs.readdir(dir);if(names.length>4096)throw Error('Pipeline cleanup scan limit');const removed:string[]=[];for(const name of names){if(!/^[a-f0-9-]{36}\.json$/.test(name))continue;const p=join(dir,name),st=await fs.lstat(p);if(!st.isFile()||st.isSymbolicLink()||st.uid!==ds.uid||(st.mode&0o077)||st.size>64000)continue;const lease=await receiptLease(name.slice(0,-5));try{const bytes=await fs.readFile(p);let record;try{record=JSON.parse(bytes.toString());}catch{continue;}if(record?.kind!=='falatrace-pipeline-review'||record.execution==='running')continue;const review=record?.review;const expiry=record?.revoked===true&&record.version===1&&record.id===name.slice(0,-5)?record.expiresAt:review?.version===1&&review.id===name.slice(0,-5)&&record.sha256===hash(review)?review.expiresAt:undefined;if(!Number.isFinite(expiry)||expiry>now)continue;if(dryRun)removed.push(name.slice(0,-5));if(!dryRun){const current=await fs.lstat(p);if(current.ino!==st.ino||current.dev!==st.dev||!bytes.equals(await fs.readFile(p)))continue;await fs.unlink(p);removed.push(name.slice(0,-5));}}finally{await lease.release();}}return removed;}
import {resolve} from 'node:path';
import {acquireSingleton} from '../runtime/singleton';
const receiptLease=async(id:string)=>{const name='pipeline-receipt-'+id.replaceAll('-',''),deadline=Date.now()+5000;for(;;){try{return await acquireSingleton(name);}catch(e){if((e as Error).message!==name+' is already running'||Date.now()>=deadline)throw e;await new Promise(r=>setTimeout(r,25));}}};
/** One admitted execution per grant. Same completed destination returns only verified existing artifacts. */
export async function withPipelineVisualClaim(id:string,consentKey:string,binding:{jobId:string;outputDir:string;sessionRoot:string},run:()=>Promise<void|{committedGrantId:string}>){
 const owner=hash({job:binding.jobId,output:resolve(binding.outputDir),session:resolve(binding.sessionRoot)}),execution=await acquireSingleton('pipeline-execution-'+id.replaceAll('-',''));
 try{let lease=await receiptLease(id);try{const review=await read(id);if(review.consentKey!==consentKey)throw Error('Pipeline consent key differs');const record=await readStored(id,false,true);if(record.owner&&record.owner!==owner)throw Error('Pipeline grant already bound to another job/destination');if(record.execution==='completed'){for(const [name,expected] of Object.entries(record.artifacts||{})){if(!['visual-summary.json','visual-summary.md','visual-summary-evidence.json'].includes(name))throw Error('Invalid completed grant artifact');const file=join(binding.outputDir,name),st=await fs.lstat(file);if(!st.isFile()||st.isSymbolicLink()||st.size>8*1024*1024||createHash('sha256').update(await fs.readFile(file)).digest('hex')!==expected)throw Error('Completed visual result changed; fresh preview required');}if(Object.keys(record.artifacts||{}).length!==3)throw Error('Missing completed grant artifacts');return;}if(record.execution)throw Error('Pipeline grant already consumed; fresh preview required');record.owner=owner;record.execution='running';await writeRecord(id,record);}finally{await lease.release();}
 try{const result=await run();if(result?.committedGrantId===id)return;const artifacts:Record<string,string>={};for(const name of ['visual-summary.json','visual-summary.md','visual-summary-evidence.json']){const f=join(binding.outputDir,name),st=await fs.lstat(f);if(!st.isFile()||st.isSymbolicLink()||st.size>8*1024*1024)throw Error('Unsafe completed grant artifact');artifacts[name]=createHash('sha256').update(await fs.readFile(f)).digest('hex');}lease=await receiptLease(id);try{const record=await readStored(id,false,true);if(record.owner===owner&&record.execution==='completed'&&hash(record.artifacts)===hash(artifacts))return;await read(id,false);if(record.owner!==owner||record.execution!=='running')throw Error('Pipeline grant changed during completion');record.execution='completed';record.artifacts=artifacts;await writeRecord(id,record);}finally{await lease.release();}
 }catch(error){lease=await receiptLease(id);try{let record;try{record=await readStored(id,false,true);}catch{record=undefined;}if(record?.owner===owner&&record.execution==='running'){record.execution='failed';await writeRecord(id,record);}}finally{await lease.release();}throw error;}
 }finally{await execution.release();}
}

export const pipelineSessionIdentity=(adapter:string,review:Pick<PipelineReview,'id'|'planKey'|'scope'>)=>'pipeline-scoped-v1:'+hash({adapter,grant:review.id,plan:review.planKey,scope:review.scope.key});
/** Commit is admitted under a live receipt; expiry after admission cannot turn a committed result into failure. */
export async function commitPipelineVisualReview(id:string,consentKey:string,binding:{jobId:string;outputDir:string;sessionRoot:string},write:()=>Promise<void>){const lease=await receiptLease(id);try{const review=await read(id);if(review.consentKey!==consentKey)throw Error('Pipeline consent differs at commit');const record=await readStored(id,false,true);if(record.execution!=='running')throw Error('Pipeline commit requires admitted execution');const owner=hash({job:binding.jobId,output:resolve(binding.outputDir),session:resolve(binding.sessionRoot)});if(record.owner!==owner)throw Error('Pipeline commit owner differs');const outputDir=binding.outputDir;await write();const artifacts:Record<string,string>={};for(const name of ['visual-summary.json','visual-summary.md','visual-summary-evidence.json']){const f=join(outputDir,name),st=await fs.lstat(f);if(!st.isFile()||st.isSymbolicLink()||st.size>8*1024*1024)throw Error('Unsafe pipeline commit artifact');artifacts[name]=createHash('sha256').update(await fs.readFile(f)).digest('hex');}record.execution='completed';record.artifacts=artifacts;await writeRecord(id,record);return {committedGrantId:id};}finally{await lease.release();}}
import type {LocalVisualAdapter} from './session';
export function assertPipelineAdapter(adapter:LocalVisualAdapter,visionEndpoint:string,selectorModel:string,visionModel:string){const b=adapter.binding;if(!b||adapter.localOnly!==true||b.endpoint!==new URL(visionEndpoint).origin||b.selectorModel!==selectorModel||b.visionModel!==visionModel||adapter.identity!==localOllamaAdapterIdentity(visionEndpoint,selectorModel,visionModel))throw Error('Pipeline adapter/model/endpoint binding differs');}
