import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

FtDialog {
    id: framesDialog; objectName: "framesDialog"
    property alias frameQuestion: frameQuestion
    property alias frameScroll: frameScroll
    property alias frameSeconds: frameSeconds
    property alias plannerTranscriptConsent: plannerTranscriptConsent
    property alias scopeEnd: scopeEnd
    property alias scopeStart: scopeStart
    property alias frameCancelButton: frameCancelButton
    property alias frameColumn: frameColumn
    property alias frameSummaryModel: frameSummaryModel
    property alias frameVisionModel: frameVisionModel
    title: mockFramesEnabled ? t("Frames · ensaio local com mock") : t("Frames · análise local sob consentimento")
    anchors.centerIn: parent; width: Math.min(window.width - 64, 560)
    height: Math.min(implicitHeight, window.height - 64)
    modal: true; closePolicy: Popup.CloseOnEscape
    onOpened: { frameQuestion.text = t("O que falta verificar neste momento?"); frameSeconds.text = "0"; frameScope=({}); scopeStart.text="0"; scopeEnd.text=""; plannerTranscriptConsent.checked=false; uxError = "" }
    onClosed: selectionChanged()
    contentItem: ScrollView {
      id: frameScroll; clip: true; contentWidth: availableWidth; implicitHeight: frameColumn.implicitHeight
      ColumnLayout {
        id: frameColumn; width: frameScroll.availableWidth; spacing: 12
        Label { objectName: "processingWaitLabel"; visible: !!processingWait; text: t("Fila global · ") + t(processingWait); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: warningColor; Layout.fillWidth: true }
        Label { text: mockFramesEnabled ? t("Preview: extração local limitada · provider mock-local, nenhuma IA real. Preview baseado no transcript, tempo aproximado. Budget: 8 previews/4 inferências mock por sessão. Abrir esta tela não chama o mock.") : t("Ollama loopback apenas. Verificar modelos consulta metadados; preview extrai localmente. Só Confirmar envia o frame/pergunta à visão e transcrição/observações ao resumo. Budget comum da instalação: limites e período abaixo após verificar modelos. 24/16 são defaults temporários alpha, configuráveis explicitamente; não são orçamento financeiro. Falhas consomem; sem reset por sessão. Nenhuma assinatura/API externa é usada."); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled; text: t("Provider: Ollama local · modelos explícitos (não salva configuração)"); wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        FtTextField { id: frameVisionModel; objectName: "frameVisionModel"; visible: !mockFramesEnabled; placeholderText: t("Modelo instalado com capability vision"); Accessible.name: t("Modelo local de visão"); Layout.fillWidth: true; maximumLength: 200; onTextEdited: { cancelFramePreview(); frameCapability=({}) } }
        FtTextField { id: frameSummaryModel; objectName: "frameSummaryModel"; visible: !mockFramesEnabled; placeholderText: t("Modelo instalado com capability completion"); Accessible.name: t("Modelo local para resumo"); Layout.fillWidth: true; maximumLength: 200; onTextEdited: { cancelFramePreview(); frameCapability=({}) } }
        FtButton { visible: !mockFramesEnabled; text: hasPending("frames-check-models") ? t("Verificando…") : t("Verificar modelos locais"); enabled: !!selected.key && !!frameVisionModel.text && !!frameSummaryModel.text && !hasPending("frames-check-models") && !hasPending("frames-confirm"); onClicked: { cancelFramePreview(); frameCapability=({}); send("frames-check-models",selected.key,{visionModel:frameVisionModel.text,summaryModel:frameSummaryModel.text}) } }
        Label { visible: !mockFramesEnabled && !!frameCapability.id; text: t("Capabilities observadas: vision / completion · ") + (frameCapability.endpoint || "") + " · " + frameCapability.visionModel + " / " + frameCapability.summaryModel + t(" · verificação expira em 5 min"); wrapMode: Text.WordWrap; textFormat: Text.PlainText; color: accent; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled && !!frameCapability.id; text: t("Budget · usuário/instalação · período lifetime (sem renovação): ") + (frameCapability.budgetLimits ? frameCapability.budgetLimits.maxInferences + t(" inferências / ") + frameCapability.budgetLimits.maxPreviews + t(" previews") : t("indisponível")) + (frameCapability.temporaryAlphaDefaults ? t(" · defaults temporários alpha") : t(" · configuração explícita, mudanças auditadas")) + t(". Modelo local usa recursos da máquina; nenhum preço monetário estimado."); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled; text: t("Seleção explícita da transcrição · segundos absolutos do vídeo. Somente segmentos inteiros dentro do intervalo; trechos que cruzam bordas ficam omitidos."); wrapMode: Text.WordWrap; textFormat: Text.PlainText; color: muted; Layout.fillWidth: true }
        RowLayout { visible: !mockFramesEnabled; Layout.fillWidth:true; FtTextField { id:scopeStart; objectName:"scopeStart"; placeholderText:t("Início (s)"); text:"0"; maximumLength:16; Layout.fillWidth:true; Accessible.name:t("Início absoluto da seleção em segundos"); onTextEdited:selectionChanged() } FtTextField { id:scopeEnd; objectName:"scopeEnd"; placeholderText:t("Fim (s)"); maximumLength:16; Layout.fillWidth:true; Accessible.name:t("Fim absoluto da seleção em segundos"); onTextEdited:selectionChanged() } }
        FtButton { objectName:"prepareScopeButton"; visible:!mockFramesEnabled; text:hasPending("frames-scope")?t("Preparando trecho…"):t("Revisar trecho incluído e omitido"); enabled:!!selected.key && !!scopeEnd.text && !hasPending("frames-scope") && !hasPending("frames-confirm"); onClicked:prepareTranscriptScope() }
        Label { objectName:"scopeSummaryLabel"; visible:!!frameScope.id; text:frameScope.id?t("Incluído: ") + preciseClock(frameScope.startSeconds) + "–" + preciseClock(frameScope.endSeconds) + " · " + frameScope.includedCount + t(" de ") + frameScope.totalSegments + t(" segmentos · ") + frameScope.characters + "/" + frameScope.maxCharacters + t(" caracteres serializados\nOmitido: ") + frameScope.omittedCount + t(" (antes ") + frameScope.omittedBefore + t(", depois ") + frameScope.omittedAfter + t(", cruzam borda ") + frameScope.omittedIntersecting + t("). Limite: ") + frameScope.maxSegments + t(" segmentos. ") + (frameScope.withinLimits?t("Trecho abaixo disponível para revisar; nada enviado ao planner."):t("Acima do limite ou vazio: nenhum conteúdo enviado; reduza/ajuste a seleção. Sem truncamento automático.")):""; wrapMode:Text.WordWrap; textFormat:Text.PlainText; color:frameScope.withinLimits?ink:warningColor; Layout.fillWidth:true }
        Repeater { model: frameScope.segments || []; delegate: Label { required property var modelData; text:modelData.id + " · " + preciseClock(modelData.start) + "–" + preciseClock(modelData.end) + " · " + modelData.text; wrapMode:Text.WordWrap; textFormat:Text.PlainText; color:muted; Layout.fillWidth:true } }
        CheckBox { id: plannerTranscriptConsent; objectName: "plannerTranscriptConsent"; visible: !mockFramesEnabled; text: t("Autorizar somente o trecho revisado ao planner local (sem imagens)"); checked: false; enabled:!!frameScope.id && frameScope.withinLimits; Layout.fillWidth: true; onToggled: { if (!checked) cancelFramePreview() } }
        FtButton { objectName: "planFramesButton"; visible: !mockFramesEnabled; text: hasPending("frames-plan") ? t("Planejando…") : t("Decidir pelo transcript: precisa de frames?"); enabled: !!frameCapability.id && !!frameScope.id && frameScope.withinLimits && plannerTranscriptConsent.checked && !hasPending("frames-plan") && !hasPending("frames-confirm"); onClicked: planFrames() }
        Label { objectName: "plannerDecisionLabel"; visible: !!framePlan.id; text: framePlan.id ? t("Decisão: ") + framePlan.decision + " · " + framePlan.rationale + (framePlan.plannerCacheHit ? t("\nPlano reutilizado do cache; nenhuma nova inferência de planejamento.") : t("\nUma tentativa de planner local consumida.")) + (framePlan.decision === "frames" ? t("\nPlano proposto; nenhum frame enviado. Revisar fonte → preview → consentimento.") : t("\nNenhum frame solicitado/enviado; resumo existente preservado.")) : ""; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        Repeater { model: framePlan.sources || []; delegate: Label { required property var modelData; text: modelData.segmentId + t(" · citação: ") + modelData.quote; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true } }
        Repeater { model: framePlan.plan ? framePlan.plan.requests : []; delegate: Label { required property var modelData; text: preciseClock(modelData.timestampSeconds) + " · " + modelData.reason + " · " + modelData.segmentIds.join(", ") + t("\nPergunta visual: ") + modelData.question; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true } }
        FtButton { visible: framePlan.decision === "frames"; text: t("Preparar previews do plano revisado"); enabled: !!framePlan.id && !hasPending("frames-preview-plan") && !hasPending("frames-confirm"); onClicked: previewPlannedFrames() }
        Label { text: t("Pergunta"); color: ink }
        FtTextField { id: frameQuestion; objectName: "frameQuestion"; Layout.fillWidth: true; maximumLength: 1000; Accessible.name: t("Pergunta para evidência visual"); onTextEdited: cancelFramePreview() }
        Label { text: t("Horário em segundos, dentro de um segmento"); color: ink }
        FtTextField { id: frameSeconds; objectName: "frameSeconds"; Layout.fillWidth: true; maximumLength: 10; Accessible.name: t("Timestamp em segundos"); onTextEdited: cancelFramePreview() }
        FtButton { text: hasPending("frames-preview") ? t("Preview pendente…") : t("Preparar preview"); enabled: !!selected.key && (mockFramesEnabled || !!frameCapability.id) && !hasPending("frames-preview") && !hasPending("frames-confirm"); onClicked: prepareFrames() }
        Label { visible: !!framePreview.id; text: framePreview.id ? t("Origem: item selecionado · ") + preciseClock(framePreview.plan.requests[0].timestampSeconds) + " · " + framePreview.plan.requests[0].segmentIds.join(", ") + (mockFramesEnabled ? t("\n1 pedido · provider mock-local · sem custo de modelo · expira em 5 min") : t("\nDestino: ") + framePreview.endpoint + t("\nVisão: ") + framePreview.visionModel + t(" · resumo: ") + framePreview.summaryModel + t("\nEnviar: ") + (framePreview.frames ? framePreview.frames.length : 1) + t(" JPEG(s); primeiro (") + framePreview.frameBytes + t(" bytes), pergunta e metadata; depois ") + (framePreview.scope ? t("somente trecho selecionado + observações para resumo parcial.") : t("transcrição completa + observações para resumo.")) + t("\nHash mídia: ") + framePreview.mediaHash + t("\nHash transcrição: ") + framePreview.transcriptHash + t("\nFrames: ") + (framePreview.frames || []).map(function(f){return preciseClock(f.timestampSeconds) + " · " + f.bytes + t(" bytes · ") + f.sha256}).join("\n") + t("\nSaldo no preview (antes de confirmar): ") + framePreview.remainingInferences + t(" inferências comuns / ") + framePreview.remainingPreviews + t(" previews. Consentimento expira em até 5 min.")) : ""; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: accent; Layout.fillWidth: true }
        Image { visible: !!framePreview.frameData; source: framePreview.frameData || ""; Layout.fillWidth: true; Layout.preferredHeight: visible ? 100 : 0; fillMode: Image.PreserveAspectFit; Accessible.name: t("Frame local do timestamp solicitado; não é resultado de IA") }
        Repeater { model: framePreview.framePreviews ? framePreview.framePreviews.slice(1) : []; delegate: Image { required property var modelData; source: modelData.frameData; Layout.fillWidth: true; Layout.preferredHeight: 100; fillMode: Image.PreserveAspectFit; Accessible.name: t("Frame adicional do plano consentido") } }
        FtButton { text: hasPending("frames-confirm") ? t("Pedido pendente…") : (mockFramesEnabled ? t("Confirmar uso do mock local") : t("Autorizar visão + novo resumo local")); enabled: !!framePreview.id && !hasPending("frames-confirm") && !frameResult.sourceKey; onClicked: confirmFrames() }
        Label { visible: !!frameResult.sourceKey; text: (frameResult.synthetic ? t("Resultado sintético · requer revisão\n") : t("Observação do adapter local · requer revisão\n")) + (frameResult.text || ""); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        Label { visible: !!frameResult.summaryMarkdown; text: frameResult.scope ? t("Resumo parcial do intervalo selecionado · requer revisão\n") + frameResult.summaryMarkdown : t("Resumo visual solicitado · requer revisão\n") + (frameResult.summaryMarkdown || ""); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        FtButton { visible: !!frameResult.sourceKey; text: t("Ir à origem ") + preciseClock(frameResult.timestampSeconds); onClicked: followFrameReference() }
        Repeater { model: frameResult.observations || []; delegate: FtButton { required property var modelData; text: t("Origem ") + preciseClock(modelData.timestampSeconds) + " · " + modelData.uncertainty; onClicked: followAt(modelData.timestampSeconds) } }
        Label { visible: !!uxError; text: t(uxError); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: errorColor; Layout.fillWidth: true }
      }
    }
    footer: Item { implicitHeight: 52; FtButton { id: frameCancelButton; objectName: "frameCancelButton"; anchors.right: parent.right; anchors.rightMargin: 12; anchors.verticalCenter: parent.verticalCenter; text: t("Cancelar / fechar"); onClicked: framesDialog.reject() } }
}
