import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

FtDialog {
    id: framesDialog; objectName: "framesDialog"
    property alias frameQuestion: frameQuestion
    property alias frameScroll: frameScroll
    property alias frameSeconds: frameSeconds
    property alias plannerTranscriptConsent: plannerTranscriptConsent
    property alias scopeEnd: scopeEnd
    property alias scopeStart: scopeStart
    property alias frameCancelButton: frameCancelButton
    property alias frameColumn: frameColumn
    property alias frameSummaryModel: frameSummaryModel
    property alias frameVisionModel: frameVisionModel
    title: mockFramesEnabled ? "Frames · ensaio local com mock" : "Frames · análise local sob consentimento"
    anchors.centerIn: parent; width: Math.min(window.width - 64, 560)
    height: Math.min(implicitHeight, window.height - 64)
    modal: true; closePolicy: Popup.CloseOnEscape
    onOpened: { frameQuestion.text = "O que falta verificar neste momento?"; frameSeconds.text = "0"; frameScope=({}); scopeStart.text="0"; scopeEnd.text=""; plannerTranscriptConsent.checked=false; uxError = "" }
    onClosed: selectionChanged()
    contentItem: ScrollView {
      id: frameScroll; clip: true; contentWidth: availableWidth; implicitHeight: frameColumn.implicitHeight
      ColumnLayout {
        id: frameColumn; width: frameScroll.availableWidth; spacing: 12
        Label { objectName: "processingWaitLabel"; visible: !!processingWait; text: "Fila global · " + processingWait; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: warningColor; Layout.fillWidth: true }
        Label { text: mockFramesEnabled ? "Preview: extração local limitada · provider mock-local, nenhuma IA real. Preview baseado no transcript, tempo aproximado. Budget: 8 previews/4 inferências mock por sessão. Abrir esta tela não chama o mock." : "Ollama loopback apenas. Verificar modelos consulta metadados; preview extrai localmente. Só Confirmar envia o frame/pergunta à visão e transcrição/observações ao resumo. Budget comum da instalação: limites e período abaixo após verificar modelos. 24/16 são defaults temporários alpha, configuráveis explicitamente; não são orçamento financeiro. Falhas consomem; sem reset por sessão. Nenhuma assinatura/API externa é usada."; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled; text: "Provider: Ollama local · modelos explícitos (não salva configuração)"; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        FtTextField { id: frameVisionModel; objectName: "frameVisionModel"; visible: !mockFramesEnabled; placeholderText: "Modelo instalado com capability vision"; Accessible.name: "Modelo local de visão"; Layout.fillWidth: true; maximumLength: 200; onTextEdited: { cancelFramePreview(); frameCapability=({}) } }
        FtTextField { id: frameSummaryModel; objectName: "frameSummaryModel"; visible: !mockFramesEnabled; placeholderText: "Modelo instalado com capability completion"; Accessible.name: "Modelo local para resumo"; Layout.fillWidth: true; maximumLength: 200; onTextEdited: { cancelFramePreview(); frameCapability=({}) } }
        FtButton { visible: !mockFramesEnabled; text: hasPending("frames-check-models") ? "Verificando…" : "Verificar modelos locais"; enabled: !!selected.key && !!frameVisionModel.text && !!frameSummaryModel.text && !hasPending("frames-check-models") && !hasPending("frames-confirm"); onClicked: { cancelFramePreview(); frameCapability=({}); send("frames-check-models",selected.key,{visionModel:frameVisionModel.text,summaryModel:frameSummaryModel.text}) } }
        Label { visible: !mockFramesEnabled && !!frameCapability.id; text: "Capabilities observadas: vision / completion · " + (frameCapability.endpoint || "") + " · " + frameCapability.visionModel + " / " + frameCapability.summaryModel + " · verificação expira em 5 min"; wrapMode: Text.WordWrap; textFormat: Text.PlainText; color: accent; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled && !!frameCapability.id; text: "Budget · usuário/instalação · período lifetime (sem renovação): " + (frameCapability.budgetLimits ? frameCapability.budgetLimits.maxInferences + " inferências / " + frameCapability.budgetLimits.maxPreviews + " previews" : "indisponível") + (frameCapability.temporaryAlphaDefaults ? " · defaults temporários alpha" : " · configuração explícita, mudanças auditadas") + ". Modelo local usa recursos da máquina; nenhum preço monetário estimado."; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true }
        Label { visible: !mockFramesEnabled; text: "Seleção explícita da transcrição · segundos absolutos do vídeo. Somente segmentos inteiros dentro do intervalo; trechos que cruzam bordas ficam omitidos."; wrapMode: Text.WordWrap; textFormat: Text.PlainText; color: muted; Layout.fillWidth: true }
        RowLayout { visible: !mockFramesEnabled; Layout.fillWidth:true; FtTextField { id:scopeStart; objectName:"scopeStart"; placeholderText:"Início (s)"; text:"0"; maximumLength:16; Layout.fillWidth:true; Accessible.name:"Início absoluto da seleção em segundos"; onTextEdited:selectionChanged() } FtTextField { id:scopeEnd; objectName:"scopeEnd"; placeholderText:"Fim (s)"; maximumLength:16; Layout.fillWidth:true; Accessible.name:"Fim absoluto da seleção em segundos"; onTextEdited:selectionChanged() } }
        FtButton { objectName:"prepareScopeButton"; visible:!mockFramesEnabled; text:hasPending("frames-scope")?"Preparando trecho…":"Revisar trecho incluído e omitido"; enabled:!!selected.key && !!scopeEnd.text && !hasPending("frames-scope") && !hasPending("frames-confirm"); onClicked:prepareTranscriptScope() }
        Label { objectName:"scopeSummaryLabel"; visible:!!frameScope.id; text:frameScope.id?"Incluído: " + preciseClock(frameScope.startSeconds) + "–" + preciseClock(frameScope.endSeconds) + " · " + frameScope.includedCount + " de " + frameScope.totalSegments + " segmentos · " + frameScope.characters + "/" + frameScope.maxCharacters + " caracteres serializados\nOmitido: " + frameScope.omittedCount + " (antes " + frameScope.omittedBefore + ", depois " + frameScope.omittedAfter + ", cruzam borda " + frameScope.omittedIntersecting + "). Limite: " + frameScope.maxSegments + " segmentos. " + (frameScope.withinLimits?"Trecho abaixo disponível para revisar; nada enviado ao planner.":"Acima do limite ou vazio: nenhum conteúdo enviado; reduza/ajuste a seleção. Sem truncamento automático."):""; wrapMode:Text.WordWrap; textFormat:Text.PlainText; color:frameScope.withinLimits?ink:warningColor; Layout.fillWidth:true }
        Repeater { model: frameScope.segments || []; delegate: Label { required property var modelData; text:modelData.id + " · " + preciseClock(modelData.start) + "–" + preciseClock(modelData.end) + " · " + modelData.text; wrapMode:Text.WordWrap; textFormat:Text.PlainText; color:muted; Layout.fillWidth:true } }
        CheckBox { id: plannerTranscriptConsent; objectName: "plannerTranscriptConsent"; visible: !mockFramesEnabled; text: "Autorizar somente o trecho revisado ao planner local (sem imagens)"; checked: false; enabled:!!frameScope.id && frameScope.withinLimits; Layout.fillWidth: true; onToggled: { if (!checked) cancelFramePreview() } }
        FtButton { objectName: "planFramesButton"; visible: !mockFramesEnabled; text: hasPending("frames-plan") ? "Planejando…" : "Decidir pelo transcript: precisa de frames?"; enabled: !!frameCapability.id && !!frameScope.id && frameScope.withinLimits && plannerTranscriptConsent.checked && !hasPending("frames-plan") && !hasPending("frames-confirm"); onClicked: planFrames() }
        Label { objectName: "plannerDecisionLabel"; visible: !!framePlan.id; text: framePlan.id ? "Decisão: " + framePlan.decision + " · " + framePlan.rationale + (framePlan.plannerCacheHit ? "\nPlano reutilizado do cache; nenhuma nova inferência de planejamento." : "\nUma tentativa de planner local consumida.") + (framePlan.decision === "frames" ? "\nPlano proposto; nenhum frame enviado. Revisar fonte → preview → consentimento." : "\nNenhum frame solicitado/enviado; resumo existente preservado.") : ""; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        Repeater { model: framePlan.sources || []; delegate: Label { required property var modelData; text: modelData.segmentId + " · citação: " + modelData.quote; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: muted; Layout.fillWidth: true } }
        Repeater { model: framePlan.plan ? framePlan.plan.requests : []; delegate: Label { required property var modelData; text: preciseClock(modelData.timestampSeconds) + " · " + modelData.reason + " · " + modelData.segmentIds.join(", ") + "\nPergunta visual: " + modelData.question; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true } }
        FtButton { visible: framePlan.decision === "frames"; text: "Preparar previews do plano revisado"; enabled: !!framePlan.id && !hasPending("frames-preview-plan") && !hasPending("frames-confirm"); onClicked: previewPlannedFrames() }
        Label { text: "Pergunta"; color: ink }
        FtTextField { id: frameQuestion; objectName: "frameQuestion"; Layout.fillWidth: true; maximumLength: 1000; Accessible.name: "Pergunta para evidência visual"; onTextEdited: cancelFramePreview() }
        Label { text: "Horário em segundos, dentro de um segmento"; color: ink }
        FtTextField { id: frameSeconds; objectName: "frameSeconds"; Layout.fillWidth: true; maximumLength: 10; Accessible.name: "Timestamp em segundos"; onTextEdited: cancelFramePreview() }
        FtButton { text: hasPending("frames-preview") ? "Preview pendente…" : "Preparar preview"; enabled: !!selected.key && (mockFramesEnabled || !!frameCapability.id) && !hasPending("frames-preview") && !hasPending("frames-confirm"); onClicked: prepareFrames() }
        Label { visible: !!framePreview.id; text: framePreview.id ? "Origem: item selecionado · " + preciseClock(framePreview.plan.requests[0].timestampSeconds) + " · " + framePreview.plan.requests[0].segmentIds.join(", ") + (mockFramesEnabled ? "\n1 pedido · provider mock-local · sem custo de modelo · expira em 5 min" : "\nDestino: " + framePreview.endpoint + "\nVisão: " + framePreview.visionModel + " · resumo: " + framePreview.summaryModel + "\nEnviar: " + (framePreview.frames ? framePreview.frames.length : 1) + " JPEG(s); primeiro (" + framePreview.frameBytes + " bytes), pergunta e metadata; depois " + (framePreview.scope ? "somente trecho selecionado + observações para resumo parcial." : "transcrição completa + observações para resumo.") + "\nHash mídia: " + framePreview.mediaHash + "\nHash transcrição: " + framePreview.transcriptHash + "\nFrames: " + (framePreview.frames || []).map(function(f){return preciseClock(f.timestampSeconds) + " · " + f.bytes + " bytes · " + f.sha256}).join("\n") + "\nSaldo no preview (antes de confirmar): " + framePreview.remainingInferences + " inferências comuns / " + framePreview.remainingPreviews + " previews. Consentimento expira em até 5 min.") : ""; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: accent; Layout.fillWidth: true }
        Image { visible: !!framePreview.frameData; source: framePreview.frameData || ""; Layout.fillWidth: true; Layout.preferredHeight: visible ? 100 : 0; fillMode: Image.PreserveAspectFit; Accessible.name: "Frame local do timestamp solicitado; não é resultado de IA" }
        Repeater { model: framePreview.framePreviews ? framePreview.framePreviews.slice(1) : []; delegate: Image { required property var modelData; source: modelData.frameData; Layout.fillWidth: true; Layout.preferredHeight: 100; fillMode: Image.PreserveAspectFit; Accessible.name: "Frame adicional do plano consentido" } }
        FtButton { text: hasPending("frames-confirm") ? "Pedido pendente…" : (mockFramesEnabled ? "Confirmar uso do mock local" : "Autorizar visão + novo resumo local"); enabled: !!framePreview.id && !hasPending("frames-confirm") && !frameResult.sourceKey; onClicked: confirmFrames() }
        Label { visible: !!frameResult.sourceKey; text: (frameResult.synthetic ? "Resultado sintético · requer revisão\n" : "Observação do adapter local · requer revisão\n") + (frameResult.text || ""); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        Label { visible: !!frameResult.summaryMarkdown; text: frameResult.scope ? "Resumo parcial do intervalo selecionado · requer revisão\n" + frameResult.summaryMarkdown : "Resumo visual solicitado · requer revisão\n" + (frameResult.summaryMarkdown || ""); textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: ink; Layout.fillWidth: true }
        FtButton { visible: !!frameResult.sourceKey; text: "Ir à origem " + preciseClock(frameResult.timestampSeconds); onClicked: followFrameReference() }
        Repeater { model: frameResult.observations || []; delegate: FtButton { required property var modelData; text: "Origem " + preciseClock(modelData.timestampSeconds) + " · " + modelData.uncertainty; onClicked: followAt(modelData.timestampSeconds) } }
        Label { visible: !!uxError; text: uxError; textFormat: Text.PlainText; wrapMode: Text.WordWrap; color: errorColor; Layout.fillWidth: true }
      }
    }
    footer: Item { implicitHeight: 52; FtButton { id: frameCancelButton; objectName: "frameCancelButton"; anchors.right: parent.right; anchors.rightMargin: 12; anchors.verticalCenter: parent.verticalCenter; text: "Cancelar / fechar"; onClicked: framesDialog.reject() } }
}
