import {test,expect} from 'bun:test';
import {promises as fs} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
const guard=join(import.meta.dir,'../../../scripts/qa-isolation-guard.ts');
test('QA preload refuses inherited data roots before application import; strace proves no access to synthetic user sentinel',async()=>{
 const sentinel=await fs.mkdtemp(join('/tmp','qa-user-sentinel-')),inside=process.env.FALATRACE_QA_ROOT!;
 try {await fs.writeFile(join(sentinel,'keep'),'synthetic-user-keep');const before=await fs.stat(join(sentinel,'keep'));
 const script=join(inside,'guard-probe.ts'),marker=join(inside,'product-imported');await fs.writeFile(script,`await import(${JSON.stringify(join(import.meta.dir,'../../runtime/heavy-admission.ts'))}).catch(()=>{});await Bun.write(${JSON.stringify(marker)},'product import reached');`);
 const variants=[{...process.env,HOME:sentinel},{...process.env,XDG_STATE_HOME:sentinel},{...process.env,XDG_CACHE_HOME:sentinel},{...process.env,TMPDIR:sentinel},{...process.env,FALATRACE_QA_NONCE:'bad'},{...process.env,FALATRACE_QA_ISOLATED:''}];
 for(let i=0;i<variants.length;i++){const trace=join(inside,'guard-strace-'+i);const child=Bun.spawn(['/usr/bin/strace','-f','-e','trace=file','-o',trace,'/usr/bin/python3','-I',join(import.meta.dir,'../../../scripts/qa-run.py'),process.execPath,'run','--preload',guard,script],{env:variants[i],stdout:'pipe',stderr:'pipe'});expect(await child.exited).not.toBe(0);expect(await new Response(child.stderr).text()).toContain('QA refused');expect(await fs.access(marker).then(()=>true,()=>false)).toBe(false);expect(await fs.readFile(trace,'utf8')).not.toContain(sentinel);}
 const after=await fs.stat(join(sentinel,'keep'));expect(after.mtimeMs).toBe(before.mtimeMs);expect(await fs.readFile(join(sentinel,'keep'),'utf8')).toBe('synthetic-user-keep');expect(await fs.readdir(sentinel)).toEqual(['keep']);
 const raw=Bun.spawn([process.execPath,'test',join(import.meta.dir,'../../visual/__tests__/planner.test.ts')],{cwd:join(import.meta.dir,'../../..'),env:{...process.env,HOME:sentinel},stdout:'pipe',stderr:'pipe'});expect(await raw.exited).not.toBe(0);expect(await new Response(raw.stderr).text()).toContain('QA refused');expect((await fs.stat(join(sentinel,'keep'))).mtimeMs).toBe(before.mtimeMs);expect(await fs.readdir(sentinel)).toEqual(['keep']);
 }finally{await fs.rm(sentinel,{recursive:true,force:true});}
});
test('valid marked QA runs product initialization only within temporary HOME/XDG',async()=>{
 const root=process.env.FALATRACE_QA_ROOT!;const script=join(root,'guard-valid.ts');await fs.writeFile(script,`import {getRecordingStateDir} from ${JSON.stringify(join(import.meta.dir,'../../recording/session.ts'))};import {promises as fs} from 'node:fs';const dir=getRecordingStateDir();await fs.mkdir(dir,{recursive:true});await fs.writeFile(dir+'/qa-initialized','synthetic');const {heavyRoot,withHeavyAdmission}=await import(${JSON.stringify(join(import.meta.dir,'../../runtime/heavy-admission.ts'))});if(!heavyRoot().startsWith(${JSON.stringify(root+'/')}))throw Error('admission escaped QA root');await withHeavyAdmission('preview','synthetic-isolation',async()=>{});console.log(dir);`);
 const child=Bun.spawn(['/usr/bin/python3','-I',join(import.meta.dir,'../../../scripts/qa-run.py'),process.execPath,'run','--preload',guard,script],{env:process.env,stdout:'pipe',stderr:'pipe'});expect(await child.exited).toBe(0);const dir=(await new Response(child.stdout).text()).trim();expect(dir.startsWith(root+'/')).toBe(true);expect(await fs.readFile(join(dir,'qa-initialized'),'utf8')).toBe('synthetic');expect(JSON.parse(await fs.readFile(join(dir,'heavy-admission/queue.json'),'utf8'))).toEqual({version:1,queue:[]});
});
