import {test,expect} from 'bun:test';
import {promises as fs} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {DEFAULT_CONFIG} from '../src/config/defaults';
import {loadConfigSnapshot} from '../src/config/load';
import {buildAiContextFiles} from '../src/knowledge/context';
import {JobStore} from '../src/jobs/store';
import {TimeEntryStore} from '../src/timesheet/store';
test('REGRESSION: minimal enabled profile requires explicit automation and AI consent',async()=>{
 const root=await fs.mkdtemp(join(tmpdir(),'alpha6-review-config-'));
 try{const path=join(root,'config.json');const bytes=JSON.stringify({timesheet:{enabled:true}});await fs.writeFile(path,bytes);const loaded=await loadConfigSnapshot(path);expect(loaded.config.timesheet.aiClassification).toBe(false);expect(loaded.config.timesheet.automaticFromCalls).toBe(false);expect(await fs.readFile(path,'utf8')).toBe(bytes);}finally{await fs.rm(root,{recursive:true,force:true});}
});
test('REGRESSION: cleanup preserves an unknown hash-shaped file outside the empty catalog',async()=>{
 const root=await fs.mkdtemp(join(tmpdir(),'alpha6-review-cleanup-'));
 try{
  const cfg=structuredClone(DEFAULT_CONFIG);cfg.timesheet.contextPath=join(root,'catalog.json');await fs.writeFile(cfg.timesheet.contextPath,JSON.stringify({version:1,clients:[],colleagues:[],taskTypes:[]}));
  const outputDir=join(root,'output');await fs.mkdir(join(outputDir,'clients'),{recursive:true});const unknown=join(outputDir,'clients','client-'+'a'.repeat(64)+'.md');const other=join(outputDir,'clients','personal-notes.md');await fs.writeFile(unknown,'Synthetic unrelated personal note, never generated by product');await fs.writeFile(other,'Synthetic unrelated note');
  await buildAiContextFiles(cfg,{outputDir,jobStore:new JobStore(join(root,'jobs')),timeStore:new TimeEntryStore(join(root,'entries'))});expect(await fs.readFile(unknown,'utf8')).toBe('Synthetic unrelated personal note, never generated by product');expect(await fs.readFile(other,'utf8')).toBe('Synthetic unrelated note');
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
test('REGRESSION: exact client lookup resolves the requested code',async()=>{
 const {validateTimesheetContext}=await import('../src/timesheet/types');const {findClient}=await import('../src/timesheet/context');
 const catalog=validateTimesheetContext({version:1,colleagues:[],taskTypes:[],clients:[{code:'A.B',name:'Synthetic first',aliases:[],responsibleNames:[]},{code:'a-b',name:'Synthetic second',aliases:[],responsibleNames:[]}]});
 expect(findClient(catalog,'a-b')?.code).toBe('a-b');
});
test('REGRESSION: failed native build never executes a stale binary on retry',async()=>{
 const root=await fs.mkdtemp(join(tmpdir(),'alpha6-review-native-'));
 try{
  const src=join(root,'src/desktop'),dist=join(root,'dist/desktop'),sdk=join(root,'sdk'),bin=join(root,'bin');for(const p of [src,dist,bin,join(sdk,'usr/lib/qt6/libexec')])await fs.mkdir(p,{recursive:true});
  const runner=join(src,'run.ts');await fs.copyFile(new URL('../src/desktop/run.ts',import.meta.url),runner);await fs.writeFile(join(root,'package.json'),JSON.stringify({version:'9.9.9-synthetic',type:'module'}));
  for(const name of ['main.cpp','Main.qml','bridge.ts'])await fs.writeFile(join(src,name),'// synthetic review fixture');
  const moc=join(sdk,'usr/lib/qt6/libexec/moc'),compiler=join(bin,'g++'),executable=join(dist,'recording-studio');await fs.writeFile(moc,'#!/bin/sh\nexit 0\n',{mode:0o700});await fs.writeFile(compiler,'#!/bin/sh\necho SYNTHETIC_COMPILER_FAILED >&2\nexit 7\n',{mode:0o700});await fs.writeFile(executable,'#!/bin/sh\necho SYNTHETIC_OLD_BUILD\n',{mode:0o700});
  const now=Date.now()/1000;await fs.utimes(join(src,'main.cpp'),now-20,now-20);await fs.utimes(executable,now-10,now-10);
  const env={...process.env,PATH:bin+':/usr/bin:/bin',RECORDING_DESKTOP_SDK:sdk};
  const run=async()=>{const p=Bun.spawn([process.execPath,runner],{env,stdout:'pipe',stderr:'pipe'});const [code,stdout,stderr]=await Promise.all([p.exited,new Response(p.stdout).text(),new Response(p.stderr).text()]);return {code,stdout,stderr};};
  const first=await run();expect(first.code).not.toBe(0);expect(first.stderr).toContain('SYNTHETIC_COMPILER_FAILED');expect(await fs.readFile(join(dist,'build-info.h'),'utf8')).toContain('9.9.9-synthetic');
  const second=await run();expect(second.code).not.toBe(0);expect(second.stdout).not.toContain('SYNTHETIC_OLD_BUILD');expect(second.stderr).toContain('SYNTHETIC_COMPILER_FAILED');
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
